---
  - name: install_configure_tomcat
    hosts: tomcat
    gather_facts: false
    vars:
      req_java: java-1.8.0-openjdk
      tomcat_version: 8.5.85
      tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{tomcat_version.split('.')[0]}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
      tomcat_admin_user: tomcat
      tomcat_admin_password: tomcat
      tomcat_port: 8010

    become: yes
    become_user: root
    tasks:
     - name: updating repo
       yum:
          name: "*"
          state: latest

     - name: installing java
       yum:
          name: "{{req_java}}"
          state: present

     - name: Download tomcat if not installed
       get_url:
          url: "{{tomcat_url}}"
          dest: /usr/local/

     - name: Extracting downlaod tomcat
       unarchive:
          src: "/usr/local/apache-tomcat-{{tomcat_version}}.tar.gz"
          dest: /usr/local/
          remote_src: yes


     - name: Replacing default port with required port
       template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/tomcat/templates/server.xml.j2
           dest: /usr/local/apache-tomcat-{{tomcat_version}}/conf/server.xml
       become: true

     - name: Changing manager_users
       template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/tomcat/templates/manager-context.xml.j2
           dest: /usr/local/apache-tomcat-{{tomcat_version}}/webapps/manager/META-INF/context.xml
       become: true

     - name: Changing Hostmanager_users
       template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/tomcat/templates/manager-context.xml.j2
           dest:  /usr/local/apache-tomcat-{{tomcat_version}}/webapps/host-manager/META-INF/context.xml
       become: true


     - name: tomcat-user
       template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/tomcat/templates/tomcat-users.xml.j2
           dest:  /usr/local/apache-tomcat-{{tomcat_version}}/conf/tomcat-users.xml
       become: true
     - name: Deploy war file to tomcat server
       copy:
          src: /var/lib/jenkins/workspace/Ansible-Jenkins/target/LoginWebApp-2.war
          dest: /usr/local/apache-tomcat-{{tomcat_version}}/webapps
     - name: restart the tomcat server
       shell: nohup /usr/local/apache-tomcat-8.5.85/bin/startup.sh



